version: "3"
services:
 hub:
  image: selenium/hub:3.14
 chrome:
  image: selenium/node-chrome:3.14
  depends_on:
   - hub
  environment:
   - HUB_HOST=hub  
 firefox:
  image: selenium/node-firefox:3.14
  shm_size: '1gb'
  environment:
   - HUB_HOST=hub
  depends_on:
   - hub
 search-moduleFF:
  image: meghana2013/seleium-docker
  depends_on:
   - chrome
   - firefox
  environment:
   - BROWSER=firefox
   - HUB_HOST=hub
   - MODULE=search-module.xml
  volumes:
   - ./output/search-resultFF:/usr/share/udemy/test-output 
 search-moduleChrome:
  image: meghana2013/seleium-docker
  depends_on:
   - chrome
   - firefox
  environment:
   - BROWSER=chrome
   - HUB_HOST=hub
   - MODULE=search-module.xml
  volumes:
   - ./output/search-resultChrome:/usr/share/udemy/test-output 
 book-flight-moduleFF:
  image: meghana2013/seleium-docker
  depends_on:
   - chrome
   - firefox
  environment:
   - BROWSER=firefox
   - HUB_HOST=hub
   - MODULE=book-flight-module.xml
  volumes:
   - ./output/book-resultFF:/usr/share/udemy/test-output    
 book-flight-moduleChrome:
  image: meghana2013/seleium-docker
  depends_on:
   - chrome
   - firefox
  environment:
   - BROWSER=chrome
   - HUB_HOST=hub
   - MODULE=book-flight-module.xml
  volumes:
   - ./output/book-resultChrome:/usr/share/udemy/test-output    